apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    imports:
    - repositories: unfurl
      file: tosca_plugins/artifacts.yml
    topology_templates:
      node_templates:
        terraform-expl:
          type: unfurl.nodes.Installer.Terraform
            interfaces:
              defaults:
                inputs:
                  tfvars:
                    aws_machine_type: t2micro
                  main: 
                    resource "aws_instance" "management_instance" {
                      ami           = var.aws_image
                      instance_type = var.aws_instance_type

                      tags = {
                      Name = "Management-Instance"
                      }
                      vpc_security_group_ids = [ aws_security_group.allow_all.id ]            
                      key_name = "myKey1"
                    } 
                    
                    
